AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  esp32-iot
  
Globals:
  Function:
    Timeout: 3

Resources:
  RespondFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: respond/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
       
  PermissionForIoTEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RespondFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "iot.amazonaws.com"
            
  LambdaCallFromPub:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: LambdaCallFromPub
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT * FROM 'esp32/pub'
        Actions:
          - Lambda: 
              FunctionArn: !GetAtt RespondFunction.Arn

